server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdemo?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:

  #指定实体类的位置
#  type-aliases-package: com.xj.bean

#  #mapper文件的位置
#  mapper-locations: classpath:mybatis/mapper/GuestMapper.xml

  #指定mybatis配置文件位置
  config-location: classpath:mybatis-config.xml